spring:
  application:
    name: aluno-service

  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: 8093

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

wellpag:
  jwt:
    secret: ${JWT_SECRET}
  agenda-service:
    base-url: ${AGENDA_SERVICE_URL:http://localhost:8094}
  financeiro-service:
    base-url: ${FINANCEIRO_SERVICE_URL:http://localhost:8095}
