spring:
  application:
    name: pagamento-service

  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: 8096

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

wellpag:
  jwt:
    secret: ${JWT_SECRET}
  webhook:
    base-url: ${WEBHOOK_BASE_URL:http://localhost:8080}
  crypto:
    banco-config-key: ${BANCO_CONFIG_ENCRYPTION_KEY}
